name: taskobi
description: "Taskobi — Tapşırıq və TODO idarəetmə mobil tətbiqi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # HTTP & API
  dio: ^5.7.0

  # Storage
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Real-time
  socket_io_client: ^3.0.2

  # Notifications
  flutter_local_notifications: ^18.0.1

  # File handling
  file_picker: ^8.3.7
  image_picker: ^1.1.2

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.2
  intl: ^0.20.2

  # Auth
  local_auth: ^2.3.0

  # Utils
  connectivity_plus: ^6.1.4
  path_provider: any
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  # hive_generator: manual adapter istifadə edilir

flutter:
  uses-material-design: true
